### ISSUE TITLE
XML Gerado muito grande, não abrindo na resposta

### ISSUE THREAD

**Issue by gustavorios** [vtex/academy#3]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [2322](https://vtexhelp.zendesk.com/agent/#/tickets/2322)
**Priority:** normal
**Zendesk assignee:** Force/Cristiane Galante David

**Original ticket content:**

Os XMLs que são muito grandes são gerados mas não dá para ser posto na resposta:

http://www.shopfacilamex.com.br/XMLData/googleshoppingamex.xml

Com isso mostra o erro por exemplo:
This page contains the following errors:

error on line 3304 at column 911: Extra content at the end of the document
Below is a rendering of the page up to the first error.

O Renan Porto fez um recurso na tela de xml que é pra baixar o xml quando for muito grande, mas vimos que não está funcionando muito bem... tendo que colocar um link para cada xml de cada url.

Att

**Comment by gustavorios** [comment]
_Comment from Zendesk by cristiane.david@vtex.com.br at 2015-07-01 19:55:28 UTC:_

<div class="zd-comment"><p>Os XMLs que são muito grandes são gerados mas não dá para ser posto na resposta:</p>
<p><a href="http://www.shopfacilamex.com.br/XMLData/googleshoppingamex.xml">http://www.shopfacilamex.com.br/XMLData/googleshoppingamex.xml</a></p>
<p>Com isso mostra o erro por exemplo:<br>
This page contains the following errors:</p>
<p>error on line 3304 at column 911: Extra content at the end of the document<br>
Below is a rendering of the page up to the first error.</p>
<p>O Renan Porto fez um recurso na tela de xml que é pra baixar o xml quando for muito grande, mas vimos que não está funcionando muito bem... tendo que colocar um link para cada xml de cada url.</p>
<p>Att</p>
<p>Cristiane David</p></div>

**Comment by klzns** [comment]
Repositorio errado
