### ISSUE TITLE
Empório da Beleza - Flag de promoção inativa continua sendo exibida no ambiente final da loja

### ISSUE THREAD

**Issue by gustavorios** [vtex/academy#5]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [2820](https://vtexhelp.zendesk.com/agent/#/tickets/2820)
**Priority:** normal
**Zendesk assignee:** Reseller/Ludmila Neves Cavalcanti

**Original ticket content:**

Boa tarde, pessoal
Segue abaixo relato do cliente sobre erro da promoção que continua ativa, mesmo após a flag estar inativa.
Favor verificar.

Todas as minhas campanhas do Tipo “Brinde” estão com o Flag de destaque desmarcadas, porém mesmo assim estão aparecendo como destaque nos produtos. Preciso ajustar isso urgente, já são campanhas antigas, e ontem a tarde começou a dar estes erros.

Toda a loja está com o os flag de promoção aparecendo. Mesmo estando desmarcada esta opção na configuração das promoções. Todos os Acessos já foram concedidos. Na página da comunidade Vtex outro cliente também está com o mesmo problema.

**Comment by gustavorios** [comment]
_Comment from Zendesk by guilherme@quatrodigital.com.br at 2015-07-10 16:52:34 UTC:_

<div class="zd-comment"><p>Boa tarde, pessoal
<br />Segue abaixo relato do cliente sobre erro da promoção que continua ativa, mesmo após a flag estar inativa.
<br />Favor verificar.</p>
<p>Todas as minhas campanhas do Tipo “Brinde” estão com o Flag de destaque desmarcadas, porém mesmo assim estão aparecendo como destaque nos produtos. Preciso ajustar isso urgente, já são campanhas antigas, e ontem a tarde começou a dar estes erros.</p>
<p>Toda a loja está com o os flag de promoção aparecendo. Mesmo estando desmarcada esta opção na configuração das promoções. Todos os Acessos já foram concedidos. Na página da comunidade Vtex outro cliente também está com o mesmo problema.</p></div>

**Comment by gustavorios** [comment]
_Comment from Zendesk by ludmila@vtex.com.br at 2015-07-14 21:42:55 UTC:_

<div class="zd-comment"><p>Ola Guilherme,</p>
<p>Estamos com um problema na atualização das flags e uma tarefa foi aberta para o desenvolvedor proceder com a correção.<br>
Assim que o desenvolvimento finalizar a tarefa, você será notificado pelo ticket.</p>
<p>Um Abraço,</p></div>

**Comment by gustavorios** [comment]
_Comment from Zendesk by ludmila@vtex.com.br at 2015-07-14 21:42:55 UTC:_

<div class="zd-comment"><p>Ola Guilherme,</p>
<p>Estamos com um problema na atualização das flags e uma tarefa foi aberta para o desenvolvedor proceder com a correção.<br>
Assim que o desenvolvimento finalizar a tarefa, você será notificado pelo ticket.</p>
<p>Um Abraço,</p></div>

**Comment by gustavorios** [comment]
_Comment from Zendesk by ludmila@vtex.com.br at 2015-07-14 21:42:55 UTC:_

<div class="zd-comment"><p>Ola Guilherme,</p>
<p>Estamos com um problema na atualização das flags e uma tarefa foi aberta para o desenvolvedor proceder com a correção.<br>
Assim que o desenvolvimento finalizar a tarefa, você será notificado pelo ticket.</p>
<p>Um Abraço,</p></div>

**Comment by gustavorios** [comment]
_Comment from Zendesk by ludmila@vtex.com.br at 2015-07-14 21:42:55 UTC:_

<div class="zd-comment"><p>Ola Guilherme,</p>
<p>Estamos com um problema na atualização das flags e uma tarefa foi aberta para o desenvolvedor proceder com a correção.<br>
Assim que o desenvolvimento finalizar a tarefa, você será notificado pelo ticket.</p>
<p>Um Abraço,</p></div>

**Comment by klzns** [comment]
Repositorio errado
