### ISSUE TITLE
Flag Ativa sendo exibida na vitrine da página, sem estar marcada como destaque.

### ISSUE THREAD

**Issue by gustavorios** [vtex/academy#6]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [3093](https://vtexhelp.zendesk.com/agent/#/tickets/3093)
**Priority:** normal
**Zendesk assignee:** Enterprise/Ludmila Neves Cavalcanti

**Original ticket content:**

Loja:
http://emporiodabelezaonline.vtexcommercestable.com.br/
Ambiente: Stable

Cenário:
Foram criadas 3 promoções de brinde sem selecionar a flag destaque, porém as mesmas estão sendo exibidas na vitrine.
Foi retirado o css, js e verificado as promoções e brindes.

Promoções:
Flag: Uma Amostra Surpresa - http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=17
Flag: Duas Amostras Surpresas- http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=18
Flag: Quatro Amostras Surpresa- http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=19

Issue aberta por:
@ludmilaneves

**Comment by gustavorios** [comment]
_Comment from Zendesk by ludmila@vtex.com.br at 2015-07-14 21:30:59 UTC:_

<div class="zd-comment"><p>Loja:<br>
<a href="http://emporiodabelezaonline.vtexcommercestable.com.br/">http://emporiodabelezaonline.vtexcommercestable.com.br/</a><br>
Ambiente: Stable</p>
<p>Cenário:<br>
Foram criadas 3 promoções de brinde sem selecionar a flag destaque, porém as mesmas estão sendo exibidas na vitrine.<br>
Foi retirado o css, js e verificado as promoções e brindes.</p>
<p>Promoções:<br>
Flag: Uma Amostra Surpresa - <a href="http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=17">http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=17</a><br>
Flag: Duas Amostras Surpresas- <a href="http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=18">http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=18</a><br>
Flag: Quatro Amostras Surpresa- <a href="http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=19">http://emporiodabelezaonline.vtexcommercestable.com.br/admin/Site/DescontoFormv2.aspx?Id=19</a></p>
<p>Issue aberta por:<br>
@ludmilaneves</p></div>

**Comment by klzns** [comment]
Repositorio errado
